### ISSUE TITLE
Author smoke test does not delete questionnaire at the end of the test.                                                                                                        

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/eq-smoke-tests#8]
It probably should. I just had to delete about 100 questionnaires from our staging environment.
We use staging for ~demos and~ trialing new features so it's a pain to have to scroll past hundreds of smoke test entries.

**Comment by samiwel** [comment]
@yoganandkunche Any chance you can add an additional step to the test which goes back to the questionnaire list, finds the questionnaire with the name "Smoke test title" and hits the delete icon?

**Comment by jonnyshaw89** [comment]
Can we re-order it so the newest ones are at the top?

**Comment by samiwel** [comment]
That might also make sense 👍  It will be less of an issue when we associate questionnaires with user accounts.

**Comment by jonnyshaw89** [comment]
Staging also isn't an environment we should be using manually. its only designed to be used as part of the pipeline. and it will soon be being destroyed regularly.
If we are demoing etc then we should be using pre-prod

**Comment by samiwel** [comment]
Closing as this issue is no longer relevant.

 - Staging is torn down each night.
 - Ordering of questionnaires has been changed.
